export const data = {
  technologyAutosuggestion: [
    {
      _index: "technology-2021-08-05",
      _type: "technology-suggester",
      _id: "604aa11428bdde42f2b2cd4a",
      _score: null,
      _source: {
        tech_meta_seo_url: "amazon-web-services-aws-market-share",
        tech_cleaned_url: "amazonwebservicesaws",
        sub_cat_meta_seo_url: "infrastructure-as-a-service-iaas",
        meta_seo_url: "amazon-web-services-(aws)-customers",
        company_profile_image_url:
          "https://d3ml3b6vywsj0z.cloudfront.net/website/product-images/Amazon.jpg",
        domains: 560377,
        description:
          "Amazon Web Services (AWS) is a comprehensive, evolving cloud computing platform provided by Amazon that includes a mixture of infrastructure as a service (IaaS), platform as a service (PaaS) and packaged software as a service (SaaS) offerings.",
        deleted_this_month: 589,
        cat_meta_seo_url: "platform-and-storage",
        adds_this_month: 820,
        type: "technology",
        category: "Platform And Storage",
        subcategory_label: "Infrastructure-as-a-Service (IaaS)",
        subcategory: "Infrastructure-as-a-Service (IaaS)",
        company_name: "Amazon Web Services (AWS)",
        company_name_label: "Amazon Web Services (AWS)",
        subcategory_label_completion: "Infrastructure-as-a-Service (IaaS)",
      },
      sort: [560377],
    },
    {
      _index: "technology-2021-08-05",
      _type: "technology-suggester",
      _id: "604aa11428bdde42f2b2ccec",
      _score: null,
      _source: {
        tech_meta_seo_url: "whatsapp-business-market-share",
        tech_cleaned_url: "whatsappbusiness",
        sub_cat_meta_seo_url: "communication",
        meta_seo_url: "whatsapp-business-customers",
        company_profile_image_url:
          "https://d3ml3b6vywsj0z.cloudfront.net/website/product-images/Whatsapp.png",
        domains: 404905,
        description:
          "Whatsapp Business powers businesses communication with customers all over the world, so they can connect with them on WhatsApp in a simple, secure, and reliable way.",
        deleted_this_month: 2060,
        cat_meta_seo_url: "communications",
        adds_this_month: 2981,
        type: "technology",
        category: "Communications",
        subcategory_label: "Communication",
        subcategory: "Communication",
        company_name: "Whatsapp Business",
        company_name_label: "Whatsapp Business",
        subcategory_label_completion: "Communication",
      },
      sort: [404905],
    },
    {
      _index: "technology-2021-08-05",
      _type: "technology-suggester",
      _id: "5bb4165d1e3d6672781bdde5",
      _score: null,
      _source: {
        tech_meta_seo_url: "salesforce-crm-market-share",
        tech_cleaned_url: "salesforcecrm",
        sub_cat_meta_seo_url: "product-configurator",
        meta_seo_url: "salesforcecrm-customers",
        company_profile_image_url:
          "https://d3ml3b6vywsj0z.cloudfront.net/website/product-images/Salesforce_CRM.jpg",
        domains: 105102,
        description:
          "Salesforce.com, Inc. is an American cloud computing company headquartered in San Francisco, California. Though its revenue comes from a customer relationship management (CRM) product, Salesforce also sells commercial applications of social networking through acquisition and internal development.",
        deleted_this_month: 13,
        cat_meta_seo_url: "sales",
        adds_this_month: 26,
        type: "technology",
        category: "Sales",
        subcategory_label: "Product Configurator",
        subcategory: "Product Configurator",
        company_name: "Salesforce CRM",
        company_name_label: "Salesforce CRM",
        subcategory_label_completion: "Product Configurator",
      },
      sort: [105102],
    },
    {
      _index: "technology-2021-08-05",
      _type: "technology-suggester",
      _id: "5bb4165d1e3d6672781bdde6",
      _score: null,
      _source: {
        tech_meta_seo_url: "salesforce-crm-market-share",
        tech_cleaned_url: "salesforcecrm",
        sub_cat_meta_seo_url: "proposal-management",
        meta_seo_url: "salesforcecrm-customers",
        company_profile_image_url:
          "https://d3ml3b6vywsj0z.cloudfront.net/website/product-images/Salesforce_CRM.jpg",
        domains: 105081,
        description:
          "Salesforce.com, Inc. is an American cloud computing company headquartered in San Francisco, California. Though its revenue comes from a customer relationship management (CRM) product, Salesforce also sells commercial applications of social networking through acquisition and internal development.",
        deleted_this_month: 80,
        cat_meta_seo_url: "sales",
        adds_this_month: 123,
        type: "technology",
        category: "Sales",
        subcategory_label: "Proposal Management",
        subcategory: "Proposal Management",
        company_name: "Salesforce CRM",
        company_name_label: "Salesforce CRM",
        subcategory_label_completion: "Proposal Management",
      },
      sort: [105081],
    },
    {
      _index: "technology-2021-08-05",
      _type: "technology-suggester",
      _id: "5bb4165d1e3d6672781bdde7",
      _score: null,
      _source: {
        tech_meta_seo_url: "salesforce-crm-market-share",
        tech_cleaned_url: "salesforcecrm",
        sub_cat_meta_seo_url: "quoting",
        meta_seo_url: "salesforcecrm-customers",
        company_profile_image_url:
          "https://d3ml3b6vywsj0z.cloudfront.net/website/product-images/Salesforce_CRM.jpg",
        domains: 104999,
        description:
          "Salesforce.com, Inc. is an American cloud computing company headquartered in San Francisco, California. Though its revenue comes from a customer relationship management (CRM) product, Salesforce also sells commercial applications of social networking through acquisition and internal development.",
        deleted_this_month: 171,
        cat_meta_seo_url: "sales",
        adds_this_month: 1024,
        type: "technology",
        category: "Sales",
        subcategory_label: "Quoting",
        subcategory: "Quoting",
        company_name: "Salesforce CRM",
        company_name_label: "Salesforce CRM",
        subcategory_label_completion: "Quoting",
      },
      sort: [104999],
    },
  ],
  companyAutosuggestion: [
    {
      text: "sap.com",
      _index: "company-2021-10-20",
      _type: "company",
      _id: "5c3b05e0d55ae49f1b7e521c",
      _score: 461538,
      _source: {
        company_industry: "Computer Software",
        company_name: "Sap",
        company_website: "sap.com",
        company_profile_image_url:
          "https://media-exp1.licdn.com/dms/image/C560BAQEc96n9i_OFoQ/company-logo_200_200/0/1593622303687?e=2159024400&v=beta&t=kofnFN06cQgNO25d33Nb0ZZW4pDXidb88gE1YmKnRsc",
        company_location_text: "Walldorf, Baden-wurttemberg, Germany",
        company_size: "10k+",
      },
    },
    {
      text: "salesforce.com",
      _index: "company-2021-10-20",
      _type: "company",
      _id: "5c3b05dcd55ae49f1b7e4a59",
      _score: 441176,
      _source: {
        company_industry: "Internet",
        company_website: "salesforce.com",
        company_name: "Salesforce Ventures",
        company_profile_image_url:
          "https://res.cloudinary.com/crunchbase-production/image/upload/v1421288803/xyiimrm08sdkclll5sew.png",
        company_location_text: "San Francisco, California, United States",
        company_size: "11-50",
      },
    },
    {
      text: "satellogic.com",
      _index: "company-2021-10-20",
      _type: "company",
      _id: "5c3b010fd55ae49f1b775205",
      _score: 389610,
      _source: {
        company_industry: "Information Technology and Services",
        company_website: "satellogic.com",
        company_name: "Satellogic",
        company_profile_image_url:
          "https://media-exp1.licdn.com/dms/image/C4D0BAQHhX6MVg7u6Hw/company-logo_200_200/0/1596468944475?e=2159024400&v=beta&t=4W2_Rd_LYpKlzywMkLuCTJqDr34pVYuaQeUk2mKnQQo",
        company_location_text: "Montevideo, Na - Uruguay, Uruguay",
        company_size: "51-200",
      },
    },
    {
      text: "sanofi.com",
      _index: "company-2021-10-20",
      _type: "company",
      _id: "59ae98c9fb0cb91dea0c37d5",
      _score: 202702,
      _source: {
        company_industry: "Pharmaceuticals",
        company_name: "Sanofi",
        company_website: "sanofi.com",
        company_profile_image_url:
          "https://media-exp1.licdn.com/dms/image/C4E0BAQEyDj0gZTGTAw/company-logo_200_200/0/1519856212359?e=2159024400&v=beta&t=PCpJVejkEjN3omf8fyct0OCKf4kzpPo0r4kAntLfoV8",
        company_location_text: "Paris, Ile-de-france, France",
        company_size: "10k+",
      },
    },
    {
      text: "sarcos.com",
      _index: "company-2021-10-20",
      _type: "company",
      _id: "5c3b015cd55ae49f1b77bcdd",
      _score: 135338,
      _source: {
        company_industry: "Industrial Automation",
        company_website: "sarcos.com",
        company_name: "Sarcos Robotics",
        company_profile_image_url:
          "https://media-exp1.licdn.com/dms/image/C4E0BAQHOc_zf0kFPig/company-logo_200_200/0/1573154215264?e=2159024400&v=beta&t=S2Hrda9cdikTzBIV1EgdY_zBGcwAiKfx7UlloTPvkPs",
        company_location_text: "Salt Lake City, Utah, United States",
        company_size: "51-200",
      },
    },
  ],
};
